gsap.from('header',{duration:1,y: '-100%', ease: 'bounce'})
gsap.from('.hero-anime',{duration:1.5 ,y: '-100%', })
gsap.from('.about-anime',{duration:1.5 ,y: '-100%', })
gsap.from('.top-anime',{duration:1.5 ,y: '100%', })
gsap.from('.nav-link', {duration:1, opacity:0, delay:1})
gsap.from('.card-anim', {duration:2, x: '-100vw',  })
gsap.from('.text-anime', {duration:2, x: '-100vw',  })
gsap.from('.icon-anime1', {duration:1, x: '-100vw',  })
gsap.from('.icon-anime2', {duration:1, x: '100vw',  })
gsap.from('.icon-anime3', {duration:1, x: '-100vw',  })
gsap.from('.icon-anime4', {duration:1, x: '100vw',  })
gsap.from('.img-anim', {duration:2, y: '100vw',  })